### ISSUE TITLE
Jest- codemods for replacing sinonJs

### ISSUE THREAD

**Issue by anudeep1426** [skovhus/jest-codemods#100]
Please add support to migrate the sinon to jest.

**Comment by skovhus** [comment]
Note that this project is 100% community-driven. 

Most of the transformations here either originates from my own needs or contributions from the community that needed a specific feature. I'm personally not planning to implement this right now as I don't have a need for it.

So if you need Sinon support it would be awesome if you added support for this in jest-codemod. And tested it on your own codebase first to ensure that it is solid. 

I'll add a `help wanted` label. : )

**Comment by augbog** [comment]
@anudeep1426 Just FYI related issue: https://github.com/skovhus/jest-codemods/issues/68

**Comment by anudeep1426** [comment]
@augbog  Yeah we can close any of the one issue in favor of other issue.

Thanks @augbog .

**Comment by skovhus** [comment]
Duplicate. : )
