### ISSUE TITLE
Transformation error: Where to add a parser/compiler for TypeScript

### ISSUE THREAD

**Issue by c-science1** [skovhus/jest-codemods#102]
I am looking to migrate our tests from Jasmine to Jest. However, it's failing on the first step with the error below:

Transformation error SyntaxError: Unexpected token (22:8) 

It's recommended to use ts-jest but is jest-codemods configurable to allow for this or add TypeScript transformation?

**Comment by skovhus** [comment]
Hi. Thanks for reaching out.

`jscodeshift` that we use doesn't currently support TypeScript... But some people are working on it https://github.com/facebook/jscodeshift/issues/180

We should probably add this to the README.

**Comment by c-science1** [comment]
Yes definitely, it should be highlighted in the README and also https://facebook.github.io/jest/docs/en/migration-guide.html where it mentions Jasmine but not TypeScript which go hand in hand....

It would have saved me a day's worth of effort trying to make it work with TypeScript.

**Comment by skovhus** [comment]
> It would have saved me a day's worth of effort trying to make it work with TypeScript.

Sorry to hear that.

Both this and Jest is open source and welcome contributions. Let me know if you would like to contribute here by updating the README. : )

**Comment by c-science1** [comment]
Yes sure, thanks for letting me know, will update the ReadME file :) 
Currently ooking into https://www.npmjs.com/package/babel-preset-typescript to be added to babel as a preset but can't find .bablerc file...any ideas where I can add this new preset?

**Comment by skovhus** [comment]
Replaced by https://github.com/skovhus/jest-codemods/issues/122
