### ISSUE TITLE
AVA: snapshot(expected, [message]) => .toMatchSnapshot(message)

### ISSUE THREAD

**Issue by wmertens** [skovhus/jest-codemods#104]
AVA can pass a message to the snapshot, so does expect, it would be nice if the codemod retained that.

**Comment by skovhus** [comment]
Thanks.

The message that you pass to AVA or Expect, is than an error message or the name of the snapshot?

In Jest it is the name of the snapshot.

Feel free to submit a PR for this. : )

**Comment by wmertens** [comment]
It is the name of the snapshot, in fact, when I did this, the .md
output between AVA and Jest was identical.

I actually took a quick look to see if I could do it, but didn't
immediately see where to begin 😅. Any hints?

**Comment by skovhus** [comment]
I suggest starting with having a failing test demonstration what you want to achieve. 

See https://github.com/skovhus/jest-codemods/blob/master/src/transformers/ava.test.js

Also adding a PR with a failing test is a good contribution. 👍

**Comment by skovhus** [comment]
This was released in April
