### ISSUE TITLE
Improve mocha transformer (webpack feedback)

### ISSUE THREAD

**Issue by skovhus** [skovhus/jest-codemods#109]
See https://github.com/webpack/webpack/commit/5a8083a930ce55df959340fb4ea8d9cdcc42913b#commitcomment-28797796

**Comment by niieani** [comment]
I think the codemods crashed on some files altogether, in some cases. You'll need to try it out yourself to see where things went wrong! :)

**Comment by skovhus** [comment]
@niieani thanks.

I've checked out `webpack` (commit: https://github.com/webpack/webpack/pull/6396/commits/009772cb20bed0d5fb192b39fac48a2a84b03ad2) and ran jest-codemods on the entire `test` folder. It gives the following result:

jest-codemods@0.13.x (with jscodeshift@0.3):
122 errors / 278 ok

`jest-codemods` mainly fails due to all the invalid .js files with test fixtures. But there is also some issues with the babylon parser and issues with unsupported `should.js` constructs (`expect(typeof id).to.be.oneOf("number", "string")`).

After upgrading jscodeshift, then result now looks a bit better.

jest-codemods@0.14.x jscodeshift@0.5:
46 errors / 299 ok

### TODO
- [x] upgrade jscodeshift (released as `jest-codemods@0.14.0`)
- [ ] support `oneOf`

**Comment by skovhus** [comment]
Replaced by https://github.com/skovhus/jest-codemods/issues/116
