### ISSUE TITLE
Support Chai assert with globals

### ISSUE THREAD

**Issue by brianmhunt** [skovhus/jest-codemods#119]
It seems from the chai-assert code here that `import {assert} from 'chai'` is needed in order for the chai plugin to work.

Is there a way to get the Chai transform to work without having the import? i.e. for those of us with `global.assert = chai.assert`.

Many thanks.

**Comment by skovhus** [comment]
We usually use detection of import/require statement whenever possible. But maybe there should be a way of bypassing this safety check... although this might lead to some false positives. 

Any suggestions?

**Comment by brianmhunt** [comment]
From an end-user perspective, it's certainly better to have a flag that forces chai replacement, as opposed to adding a stub line to every test file.

**Comment by skovhus** [comment]
Wondering if we should just convert more aggressively without the require/import detection. That means more false positives, but hopefully, people are working with version control. 

It could be a question in the CLI.

**Comment by skovhus** [comment]
@brianmhunt can you check if `jest-codemods@0.16.0` does what you expect? I've added a CLI option, see https://github.com/skovhus/jest-codemods/pull/131.

**Comment by brianmhunt** [comment]
Thanks @skovhus ; It looks right to me. If I discover any issues with further use, I'll open a new issue.
