### ISSUE TITLE
Support for TypeScript

### ISSUE THREAD

**Issue by ericlam51** [skovhus/jest-codemods#122]
I  would like to transition our Mocha Chai test suite into Jest however, there are all written in TypeScript. Is there any plans to support TypeScript I am sure it will be greatly appreciated by many?

**Comment by skovhus** [comment]
I would love to support TypeScript! Problem is the underlying libraries we are using...

`jscodeshift` has recently made some progress to support TypeScript. If you are up for it, please try to contribute to some of these issues/PRs:
- https://github.com/facebook/jscodeshift/issues/180
- https://github.com/facebook/jscodeshift/pull/269
- https://github.com/facebook/jscodeshift/pull/239#issuecomment-367760997

Related https://github.com/skovhus/jest-codemods/issues/102

**Comment by domoritz** [comment]
0.6.0 supports typescript. Can you update?

**Comment by skovhus** [comment]
Great! 

Besides upgrading jscodeshift I would like us to add a small integration test that documents the support. 

Are you up for doing a PR?

**Comment by domoritz** [comment]
Unfortunately no but I look forward to using it when it works.

**Comment by skovhus** [comment]
@domoritz @ericlam51 I've just released 0.18.0 with TypeScript support. 🍾 

Please try it out, and let me know if it works for you.

Thanks for your patience.

**Comment by skovhus** [comment]
If you do experience any issues with the codemod, please create a new issue with reproducible steps.
