### ISSUE TITLE
Incorrect transformation of `.to.be.an('array').that.is.empty`

### ISSUE THREAD

**Issue by deser** [skovhus/jest-codemods#125]
`expect(iAmAnArray)).to.be.an('array').that.is.empty;`
 is converted to
 `expect(Array.isArray(iAmAnArray)).toHaveLength(0);`

**Comment by skovhus** [comment]
Thanks! Let me know if you want to create a PR for this.

**Comment by deser** [comment]
Possibly later, but I can do it

**Comment by snekse** [comment]
I was under the impression that `.to.be.` type chains were not supported yet by this library?  Is that not correct?

I had some original code of `expect(component).to.not.be.false;` that wasn't touched by the transformation.

**Comment by skovhus** [comment]
> I was under the impression that .to.be. type chains were not supported yet by this library? Is that not correct?

@snekse `to.be.` is supported by the chai-should transformer. Example https://github.com/skovhus/jest-codemods/blob/master/src/transformers/chai-should.test.js#L294

I'm wondering which transformer you selected in the CLI.

**Comment by skovhus** [comment]
@deser 0.17.0 includes some improved `chai-should` conversions. Thanks for reporting this.

**Comment by deser** [comment]
Ok, many thanks and sorry for not fixing that
