### ISSUE TITLE
Filename matching is broken (at least on windows)

### ISSUE THREAD

**Issue by realtytab** [skovhus/jest-codemods#128]
Doesn't work in: GIT CMD, Git Bash, Cygwin, Node.JS command prompt.,
I have to transform each file individually; super annoying.

c:\workspaces\sts-3.9.0-git\indigo\main\IndigoRetailerUI\test>jest-codemods -d services\api\**.js
? Which test library would you like to migrate from? Mocha
? Will you be using Jest on Node.js as your test runner? Yes, use the globals provided by Jest (recommended)
? Would you like to include assertion transformations with Mocha? Expect.js (by Automattic)
Executing command: jscodeshift -t C:\Users\Lucas.Lopatka\AppData\Local\Yarn\config\global\node_modules\jest-codemods\dist\transformers\mocha.js services\api\**.js --dry
Skipping path services\api\**.js which does not exist.
No files selected, nothing to do.
(node:61476) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Function.all (<anonymous>)
    at getAllFiles.then.then.pendingWorkers (C:\Users\Lucas.Lopatka\AppData\Local\Yarn\config\global\node_modules\jscodeshift\src\Runner.js:261:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:61476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:61476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Executing command: jscodeshift -t C:\Users\Lucas.Lopatka\AppData\Local\Yarn\config\global\node_modules\jest-codemods\dist\transformers\expect-js.js services\api\**.js --dry
Skipping path services\api\**.js which does not exist.
No files selected, nothing to do.
(node:34984) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Function.all (<anonymous>)
    at getAllFiles.then.then.pendingWorkers (C:\Users\Lucas.Lopatka\AppData\Local\Yarn\config\global\node_modules\jscodeshift\src\Runner.js:261:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:34984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:34984) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

c:\workspaces\sts-3.9.0-git\indigo\main\IndigoRetailerUI\test>dir services\api\
 Volume in drive C is Windows
 Volume Serial Number is 9877-133C

 Directory of c:\workspaces\sts-3.9.0-git\indigo\main\IndigoRetailerUI\test\services\api

08/29/2018  04:03 PM    <DIR>          .
08/29/2018  04:03 PM    <DIR>          ..
08/29/2018  04:03 PM             2,217 AccessControllerService.spec.js
05/30/2018  04:24 PM             5,552 BasicErrorControllerService.spec.js
05/30/2018  04:24 PM            37,717 CodeTypeControllerService.spec.js
05/30/2018  04:24 PM            23,641 CustomerControllerService.spec.js
05/30/2018  04:24 PM            26,033 DealControllerService.spec.js
05/30/2018  04:24 PM             2,121 IndexControllerService.spec.js
05/30/2018  04:24 PM            20,366 InventoryControllerService.spec.js
05/30/2018  04:24 PM             5,768 LenderControllerService.spec.js
05/30/2018  04:24 PM            16,712 UserControllerService.spec.js
               9 File(s)        140,127 bytes
               2 Dir(s)  28,400,160,768 bytes free

c:\workspaces\sts-3.9.0-git\indigo\main\IndigoRetailerUI\test>jest-codemods -d services\api\AccessControllerService.spec.js
? Which test library would you like to migrate from? Mocha
? Will you be using Jest on Node.js as your test runner? Yes, use the globals provided by Jest (recommended)
? Would you like to include assertion transformations with Mocha? Expect.js (by Automattic)
Executing command: jscodeshift -t C:\Users\Lucas.Lopatka\AppData\Local\Yarn\config\global\node_modules\jest-codemods\dist\transformers\mocha.js services\api\AccessControllerService.spec.js --dry
Processing 1 files...
Spawning 1 workers...
Running in dry mode, no files will be written!
Sending 1 files to free worker...
All done.
Results:
0 errors
0 unmodified
0 skipped
1 ok
Time elapsed: 1.068seconds
Executing command: jscodeshift -t C:\Users\Lucas.Lopatka\AppData\Local\Yarn\config\global\node_modules\jest-codemods\dist\transformers\expect-js.js services\api\AccessControllerService.spec.js --dry
Processing 1 files...
Spawning 1 workers...
Running in dry mode, no files will be written!
Sending 1 files to free worker...
All done.
Results:
0 errors
1 unmodified
0 skipped
0 ok
Time elapsed: 0.900seconds

c:\workspaces\sts-3.9.0-git\indigo\main\IndigoRetailerUI\test>

**Comment by realtytab** [comment]
GitHub is stripping out slashes: jest-codemods -d services\\api\\*.js

**Comment by skovhus** [comment]
Thanks for reporting this. 

Please feel free to create a PR to fix this.

**Comment by skovhus** [comment]
Note that `-d` is not a supported CLI argument.

**Comment by skovhus** [comment]
Did you try `jest-codemods services/api`?

**Comment by skovhus** [comment]
Ping @realtytab

**Comment by deser** [comment]
Seems I'm experiencing the same issue 
Nothing from below works:
1. `src/*spec.js`
2. `src/**/*spec.js`
3.  `<fullpath>/*spec.js`

**Comment by skovhus** [comment]
@deser can you send me the entire command you run and the output. Preferably as a screenshot?

Thanks

**Comment by skovhus** [comment]
@deser any news here? 

Note that you can always run jest-codemods on all js files instead of just test files. So you can use `src` as a path instead of a glob.

**Comment by deser** [comment]
Oh, sorry, I didn't see your previous comment. 
I've resolved my issue (somehow, I don't remember how :) ) a few months ago so I can't help with that now :(
