### ISSUE TITLE
t.plan => expect.assertions

### ISSUE THREAD

**Issue by browniefed** [skovhus/jest-codemods#13]
https://github.com/facebook/jest/pull/2133 this will hopefully land soon, and that means `t.plan` will be supported as `expect.assertions`

**Comment by skovhus** [comment]
Thanks for highlighting this! : )

**Comment by browniefed** [comment]
It landed this morning. Never done any codemod work but I'll add the mod later this week.

**Comment by skovhus** [comment]
Thanks. It is fun! ; )

**Comment by skovhus** [comment]
Let me know if you need any help or pointers.

**Comment by browniefed** [comment]
Ah, still planning on this, just got held up on some stuff. Throwing it on my todo list

**Comment by skovhus** [comment]
Not to stress you. Take your time. 😊

**Comment by skovhus** [comment]
Thanks for contributing @browniefed ! Release as 0.7.0
