### ISSUE TITLE
Chai assert.isTrue() isn't converted to expect.toBeTruthy()

### ISSUE THREAD

**Issue by alundiak** [skovhus/jest-codemods#130]
jest-codemods v 0.15.0

Chai assert.isTrue()
https://www.chaijs.com/api/assert/

Jest expect.toBeTruthy()
https://jestjs.io/docs/en/expect#tobetruthy

**Comment by skovhus** [comment]
Thanks for reporting this. Let me know if you want to submit a PR for this.

**Comment by skovhus** [comment]
>  and first steps I faced with bug (not expected behavior) I don't like it :)

`jest-codemods` is open source and by no means perfect, but as this is open source it is up to everyone to improve it. 

https://github.com/skovhus/jest-codemods/blob/master/src/transformers/chai-assert.js#L70 should currently handle the conversion from `isTrue` to `toBe`. 

Please provide a minimal example that the code mod doesn't handle. 

Thanks.

**Comment by alundiak** [comment]
@skovhus  does it mean that jest using Chai Assert? If so why not to reuse the same name?
Anywya I'm going to try also toBe().

PS. Facebook is a huge company, and I would expect from it proper code quality. If Facebook is eager to load my mind with ads on Facebook, let's rather implement better Jest, if it's really about better tool, not about earning money on simple wrappers on already existed open source products. I principally don't want to use Mocha, Chai, Karma, if Jest really replace this all, but if I have more pain from jest, then .... sad.

**Comment by alundiak** [comment]
back to to `toBe()` as I see it is for expect:
```
 expect(data).toBe('peanut butter');
```

not for assert.toBe() as alias. Or how it works with those transformation? 
So far I want to remain using assert if possible and avoid using expect.
Not really matter to me in regards of flavor, but I wanna do less silly code line replacement work.

**Comment by skovhus** [comment]
jest-codemods isn’t backed by Facebook!

I’ve spent my weekends building it with the open source community. If it doesn’t help you, then please don’t use it. 

Personally, I’m proud that jest-codemods have helped Netflix, Spotify, Microsoft, PayPal and hundreds of other companies and open sources libraries to migrate their codebase to Jest. 

If you want to help, then give me a reproducible example of an entire test file before running the migration. Else I’m going to close this issue. 

And Jest is not a wrapper around any of the mentioned libraries.

**Comment by alundiak** [comment]
My code is simple - in my first post. rest of code is my commercial code sugar.
Even if I create jsfiddle it might even work, not sure. Going to try from home.

**Comment by alundiak** [comment]
```
describe('suit 1', () => {
  test('case 1', () => {
    const abc = true;
    // this line written for assert aka commonjs-assert or mocha/chai-assert, where assert.isTrue() function exists;
    assert.isTrue(abc);
    // after jest-codemods transform it should be smth using from expect toBeTruthy() or toBe()
  });
});
```

then I run `jest-codemods` select "all..." and globals...

And after transforming process my file/code

**Comment by skovhus** [comment]
How does you assert import/require statement look?

**Comment by alundiak** [comment]
Here is my `jest.config.js`

```
module.exports = {
  testRegex: 'test/abc.js',
  setupFiles: [
    '<rootDir>/setup-test-env.js'
  ],
  collectCoverage: true,
  collectCoverageFrom: [
    'src/*.{js,jsx}'
  ]
};
```

Here is my `setup-test-env.js`:

```
import assert from 'assert';
global.assert = assert;
```

Here is my package.json:

```
{
  "scripts": {
    "test": "jest"
  },
  "dependencies": {
    "jest": "^23.6.0"
  }
}
```

yes, `assert` is not added as dependency explicitly, but I expected that `jest` instals it somhow, or at least peerDeps, but not.
So instead commonjs-assert, built-in used.

And here is my npm ls:

[abc-ls.log](https://github.com/skovhus/jest-codemods/files/2393789/abc-ls.log)

**Comment by skovhus** [comment]
Okay. We have two issues: 
1) you are not using a library that is supported 
2) you have no import/require statements in your tests but depends on `global.assert`

### Unsupported assertion library
You are using https://github.com/defunctzombie/commonjs-assert , not Chai. That library is currently not supported by jest-codemods (see the [README](https://github.com/skovhus/jest-codemods#-jest-codemods-)).

It might be that you can use the  `chai-assert` transformer that is part of `jest-codemods`.

### No import/require statements for assertion library
Normally we are rather conservative, so our transformers only run if we detect the assertion library from import or require statements. We don't want to convert any source code using node assert for  example. 

If you want to reuse the `chai-assert` transformer (not sure if they are compatible), we detect if you are actually using chai by looking at the import/require statements. 

So you can try to add `import { assert } from 'chai';` on the top of your test files and run the codemod again.

**Comment by skovhus** [comment]
We did talk about a way to bypass the input/require detection here https://github.com/skovhus/jest-codemods/issues/119

**Comment by alundiak** [comment]
Assuming my test written using Chai Assert,
I can verify, that:
- I `npm install chai --save-dev` then 
- I added line to my test file `import { assert } from 'chai';` and then 
- executing `jest-codemods` with "Chai Assertion" selection, in fact transformed all assert-s into expect-s, and 
- it removed `import` line from code in test file.

Somehow is OK for me, coz I realize, that explicit import must have been used, so that jest-codemods transforms it properly - all tests are passed OK.

Btw, I did this with old version of jest-codemods.

PS. But in package.json `chai` remained.
@skovhus is it expected behavior, or u have code somewhere which checks if chai must be also removed/uninstalled?

**Comment by skovhus** [comment]
Good to hear. 

Yeah, the codemod doesnt touch your package.json file.

**Comment by alundiak** [comment]
UPD: Chai assert.isTrue() converted to expect.toEqual(true). I thought it would convert to expect.toBeTruthy() but ok.

**Comment by skovhus** [comment]
> UPD: Chai assert.isTrue() converted to expect.toEqual(true). I thought it would convert to expect.toBeTruthy() but ok.

`toBeTruthy()` is more relaxed than `assert.isTrue()`, as it checks if the given value is true in a boolean context. Meaning `expect('foo').toBeTruthy()` is true, but `expect('foo').toEqual(true)` is not. See https://jestjs.io/docs/en/expect#tobetruthy
