### ISSUE TITLE
Support node-tap

### ISSUE THREAD

**Issue by robcresswell** [skovhus/jest-codemods#138]
The `tape` converter mostly works fine for [node-tap](https://www.node-tap.org/), except that it explicitly requires `tape` as part of the mod. It'd be great if this could be changed to look for either `tap` or `tape`.

**Comment by skovhus** [comment]
I like it! Do you want to give it a try?

**Comment by robcresswell** [comment]
Absolutely, I'll do it this weekend

**Comment by skovhus** [comment]
@robcresswell awesome! Let me know if you have any questions.

**Comment by krainboltgreene** [comment]
Simply changing `'tape'` to `tap` successfully worked for me.

**Comment by skovhus** [comment]
Might still be nice to add this. 

Which line did you change?
