### ISSUE TITLE
Chai's `to.have.string` converted incorrectly when string literal isn't used

### ISSUE THREAD

**Issue by bjohn465** [skovhus/jest-codemods#153]
When migrating using the "Chai: Should/Expect BDD Syntax" library option, `to.have.string` is converted incorrectly when the value being checked is not a string literal.

Sample input code:
```
expect('string literal').to.have.string('literal');

const myString = 'string constant';
expect(myString).to.have.string('constant');
```

Sample output code:
```
expect('string literal').toContain('literal');

const myString = 'string constant';
expect(myString).toEqual(expect.arrayContaining(['constant']));
```

I would expect `expect(myString).to.have.string('constant');` to be converted to `expect(myString).toContain('constant');`, like the `expect('string literal')` was, since `expect.arrayContaining` won't work for strings.

It looks like this bit of code is where the check happens for a string literal: https://github.com/skovhus/jest-codemods/blob/0.19.1/src/transformers/chai-should.js#L534-L538

Perhaps the string case (https://github.com/skovhus/jest-codemods/blob/0.19.1/src/transformers/chai-should.js#L520) should be moved to its own `case` block that always returns a `toContain` call.

[The Chai documentation for `string`](https://www.chaijs.com/api/bdd/#method_string) indicates that `string` is only used to search for a substring within a given string:
> Asserts that the target string contains the given substring `str`.

**Comment by skovhus** [comment]
Thanks for the contribution!
