### ISSUE TITLE
Mocha

### ISSUE THREAD

**Issue by skovhus** [skovhus/jest-codemods#16]
@paularmstrong started integrating https://github.com/paularmstrong/mocha-to-jest-codemod into jest-codemods. This adds transformation of Mocha and Chai asserts. Great stuff! 

There are a few thing to be done
- [x] Integration (Paul is on it)
- [x] Update README + package.json
- [x] Update migration guide in the facebook/jest repo (https://github.com/facebook/jest/pull/2232)
- [x] ~~keep track of things missing transformation (maybe as GitHub issues). Currently in README of mocha-to-jest-codemod~~
- [x] 🎉

**Comment by paularmstrong** [comment]
> keep track of things missing transformation (maybe as GitHub issues). Currently in README of mocha-to-jest-codemod

You'll get warnings for those in #17
