### ISSUE TITLE
'it' becoming 'test'

### ISSUE THREAD

**Issue by MatthewTrout** [skovhus/jest-codemods#192]
Currently if I run this migrating from mocha, in addition to the modifications I'd expect to see surrounding assertions etc, `it` is being converted to `test`.  Since `it` is an alias of `test`, I'm wondering why there's a preference over test?  Also if this is the case, is there a way of avoiding this replacement in the jest-codemods utility currently?  This creates a lot of noise in spec conversion that doesn't really need to be there.  Thanks in advance!

**Comment by SimenB** [comment]
IMO `jest-codemod` should leave those alone as `test === it` in Jest. People who care should use https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/consistent-test-it.md instead

**Comment by skovhus** [comment]
It was changed Jest docs advertise the usage of `test` instead of `it`: http://facebook.github.io/jest/docs/en/api.html#testname-fn 

See original issue (3 years ago): https://github.com/skovhus/jest-codemods/issues/64

But it makes sense to keep `it` if the user is using it.

**Comment by MatthewTrout** [comment]
Thanks for the response @skovhus 
> It was changed Jest docs advertise the usage of `test` instead of `it`: http://facebook.github.io/jest/docs/en/api.html#testname-fn
> 
> See original issue (3 years ago): #64

Yeah I found that issue, but that anchor on the jest docs doesn't link to anything in the page so wondered if they'd changed their mind on that! 

> Reverting the changes in [9c1a780](https://github.com/skovhus/jest-codemods/commit/9c1a780b0362e4eb95e3923f09df65dc8fb8c6bd) should do it. @MatthewTrout let me know if you are up for creating a PR. :)

Yeah happy to do this but will simply reverting it work or will it then convert `test` to `it`?  Presumably we'd like it to just not touch `it` or `test`.

**Comment by SimenB** [comment]
Could be an option I guess?

**Comment by skovhus** [comment]
I would like to avoid too many options and have some good defaults. I think preserving what the user had makes sense. 

The link was just to the main docs where test is used instead of it. 

Reverting will not work as there has been to many changes since back then. But applying the changes manually should do the job. :)

**Comment by skovhus** [comment]
I’ll keep this open until the change is released.

**Comment by skovhus** [comment]
Released as 0.23. Thanks for your contribution!
