### ISSUE TITLE
Missing transformation for Jasmine mock return values

### ISSUE THREAD

**Issue by jwedel** [skovhus/jest-codemods#200]
The following code:
```
        focusMonitorMock = jasmine.createSpyObj('FocusMonitorMock', ['monitor', 'stopMonitoring']);
        focusMonitorMock.monitor.and.returnValue(of());
```
is transformed to:
```
    focusMonitorMock = {
      'monitor': jest.fn(),  // <-- No return value
      'stopMonitoring': jest.fn()
    };
    focusMonitorMock.monitor.and.returnValue(of());  // <-- This results in an error when running the tests
```
It should be however transformed to
```
    focusMonitorMock = {
      'monitor': jest.fn(() => of()),
      'stopMonitoring': jest.fn()
    };
```

**Comment by skovhus** [comment]
@jwedel thanks for reporting this. And let me know if you are up for creating a PR fixing this.

**Comment by jwedel** [comment]
@skovhus I've created a PR with a failing test but I have no idea how to fix this. I've looked at the `jasmine-globals.ts` but I can't figure out where to start...

**Comment by jwedel** [comment]
I figured out that it is possible to replace
```
focusMonitorMock.monitor.and.returnValue(of()); 
```
by 
```
focusMonitorMock.monitor.mockReturnValue(of()); 
```

I've changed the test and finally figured out how to write transformation that makes the tests green.

*However, I have to say that the implementation is very hard to read and understand, especially the reverse tree is messing with my mind. Moreover, IMO it's pretty bad that the actual test() call is wrapped in a reusable function. That makes debugging and running of individual tests pretty hard.*

**Comment by skovhus** [comment]
> IMO it's pretty bad that the actual test() call is wrapped in a reusable function. That makes debugging and running of individual tests pretty hard.

I see what you are saying. For running individual tests you can run `yarn test:watch` (Jest in watch mode) and filter the tests by test name. Example:
- `yarn test:watch`
- press `w` for menu
- press `t` for test name filtering
- type `maps expect within matchers` and enter

Or you can just watch failed tests or test that are modified.

**Comment by jwedel** [comment]
@skovhus Yes, that can be done. However, I am using my IDEs functionality (IntellIJ in this case) to run individual tests. But that only works if there are actual tests that can be discovered. Moreover, I don't see any need to handle it the way it is right now. I would suggest to do change the structure like that:

```
test('My name', () => {
   assertTransformation('input', 'output')
})

function assertTransformation(source, expectedOutput) {
    const result = wrappedPlugin(source)
    expect(result).toBe(expectedOutput)
}
```
That still allows using jest functionalility plus using an IDE to run tests.

**Comment by skovhus** [comment]
> I would suggest to do change the structure like that:

That is a great idea. Let me know if you are up for fixing it. :)

**Comment by jwedel** [comment]
> > I would suggest to do change the structure like that:
> 
> That is a great idea. Let me know if you are up for fixing it. :)

Done with #202 thanks to heavy use of multi-cursor actions :)
