### ISSUE TITLE
jasmine-globals: Suggest relaxing matching for spyOn(..).and.xx(..)

### ISSUE THREAD

**Issue by mvindahl** [skovhus/jest-codemods#207]
In our existing test code we often create our spies during beforeEach, along the following lines:

```typescript
  let jamesBondService: SpyObject<JamesBondService>;
  // ...  
  beforeEach(() => {
    jamesBondService = jasmine.createSpyObj('JamesBondService', [
      'orderDryMartini',
    ]),
  })
  // ...
  it('smugly socialises', () => {
    // ...
    jamesBondService.orderDryMartini.and.returnValue({ shaken: true, stirred: false});
    // ...
  })
```

The `and.returnValue` is jasmine syntax and should be transformed to `mockReturnValue`.

Alas, jest-codemods only detects `and.returnValue` if it's directly chained to `spyOn()`, like in `spyOn(..).and.returnValue(..)`. The same goes for `and.callThrough` and `and.callFake`.

I suggest relaxing the matching rules. This would be fairly easy; I've played with it and removing the section at https://github.com/skovhus/jest-codemods/blob/master/src/transformers/jasmine-globals.ts#L140 does the trick. The risk is that we'd erronously match some unrelated usage of `.and.returnValue` (or of the other two methods) but I think that's a largely hypothetical concern.

If interested, I could create a PR.

**Comment by skovhus** [comment]
Thanks for raising this. I see that the use case you mention is not supported, and I agree that the workaround you present here might be worth it.

Feel free to create a PR. Would also like if you document the use case in a unit test.
