### ISSUE TITLE
Chai: `not.to.include` erroneously transformed to `toEqual(expect.arrayContaining...)`

### ISSUE THREAD

**Issue by seansfkelley** [skovhus/jest-codemods#227]
The Chai codemod seems to be sensitive to `not` ordering in some cases. Assertions of the form

```js
expect(array).not.to.contain(member);
```

are incorrectly inverted to 

```js
expect(array).toEqual(expect.arrayContaining([member]));
```

While 

```js
expect(array).to.not.contain(member);
```

results in the expected

```js
expect(array).toEqual(expect.not.arrayContaining([member]));
```

**Comment by skovhus** [comment]
Thanks for reporting. Let us know if you want to create a PR fixing this. :)

**Comment by danbeam** [comment]
@seansfkelley @skovhus i believe this was addressed in https://github.com/skovhus/jest-codemods/pull/244
