### ISSUE TITLE
doesn't convert chai `to.be.equalTo` to jest `toEqual`

### ISSUE THREAD

**Issue by kenirwin** [skovhus/jest-codemods#233]
After running jest-codemods, I had to manually convert tests like this one from chai: 
`expect(res.libguides).to.be.equalTo(['Accountancy']);`
to this is jest:
`expect(res.libguides).toEqual(['Accountancy']);`

Is that a feature that could be added in the future, or are the two sufficiently different in some cases that it could be dangerous to do so?

**Comment by skovhus** [comment]
Thanks for reporting this. It should be doable to add. Let me know if you want to help out with this. :)

**Comment by kenirwin** [comment]
I'd be interested in helping out if someone can give me a pointer on where to start. I haven't dug into the code at all.

**Comment by skovhus** [comment]
@kenirwin I've investigated this a bit. The reason why we are not currently converting `equalTo` is that it isn't mentioned in the chai [documentation](https://www.chaijs.com/api/bdd/#method_equal) or [codebase](https://github.com/chaijs/chai/search?q=equalTo). 

The additional keywords comes from the https://www.chaijs.com/plugins/chai-arrays/ plugin.

I've added support for this in https://github.com/skovhus/jest-codemods/pull/234
