### ISSUE TITLE
Feature Suggestion: Migration from outdated versions of Jest

### ISSUE THREAD

**Issue by GeorgeWL** [skovhus/jest-codemods#241]
I was hoping the codemod could handle some of the dirty work for me, but sadly not, but I've currently got a project where as part of trying to remove tech debt, we're upgrading outdated and insecure modules, and upgrading to latest jest automagically using this tool would've been nice

I have a feeling it probably would be quite difficult to implement though, so can totally understand if y'all feel it is out of spec for this codemod

**Comment by SimenB** [comment]
We originally planned to write codemods for Jest to handle API renames, but nobody had the energy to make it happen, so we never did 😀 

The ESLint plugin can do _some_ things, but it's not super extensive.

**Comment by GeorgeWL** [comment]
would help if @jest had official upgrade guides tbh, then it would be easier to do 💯

**Comment by GeorgeWL** [comment]
would help if @jest-community had official upgrade guides to be honest, then it would be easier to do 💯

**Comment by SimenB** [comment]
Yep, but that requires time and effort to write, of which volunteers often have little 🙂

**Comment by skovhus** [comment]
Doing migration from outdated version as part of jest-codemods seems a bit out of scope, which is:

> "simplify migrating JavaScript and TypeScript test files from [AVA](https://github.com/avajs/ava), [Chai](https://github.com/chaijs/chai), [Expect.js (by Automattic)](https://github.com/Automattic/expect.js), [Expect@1.x (by mjackson)](https://github.com/mjackson/expect), [Jasmine](https://github.com/jasmine/jasmine), [Mocha](https://github.com/mochajs/mocha), [proxyquire](https://github.com/thlorenz/proxyquire), [Should.js](https://github.com/tj/should.js/), [Tape](https://github.com/substack/tape) and [Node-Tap](https://github.com/tapjs/node-tap) to [Jest](https://facebook.github.io/jest/)"

But that being said I'm not opposed to the idea if someone has time for adding this. The infrastructure and required setup is already in place.
