### ISSUE TITLE
Ava to Jest: "ReferenceError: before is not defined"

### ISSUE THREAD

**Issue by ahutchings** [skovhus/jest-codemods#26]
After running jest-codemods on my Ava tests, I'm seeing exceptions: "ReferenceError: before is not defined". The stack trace is pointing to where `test.before` was transformed to `before`. Should `test.before` be transformed to `beforeAll`?

**Input**
```javascript
test.before(() => {
   sinon.stub(Date, 'now').returns(12345);
});
```

**Output**
```javascript
before(() => {
   sinon.stub(Date, 'now').returns(12345);
});
```

**Comment by skovhus** [comment]
Thanks for reporting. Yes, that look like a bug. It should be beforeAll. 👍

Not sure if Jest previously had 'before' as an alias to 'beforeAll' or why this haven't been discovered before.
