### ISSUE TITLE
Specify transformer

### ISSUE THREAD

**Issue by montogeek** [skovhus/jest-codemods#32]
Would you accept a PR that adds the possibility to specify the transformer, something like:
`jest-codemods path -f -t=mocha`?

**Comment by skovhus** [comment]
Currently we just run all of them, which should be fine as we detect import statements for tape/Ava. 

But if you have a use case for specifying the transformer I'm open to that. : )

Remember that there might be addition transformer options, like chai assertions etc.

**Comment by skovhus** [comment]
On the other hand, you can just run `jscodeshift` directly as mentioned here:
https://github.com/skovhus/jest-codemods#usage-jscodeshift

**Comment by skovhus** [comment]
Feel free to propose a PR at a later point if you still want/need this.

Thanks. : )
