### ISSUE TITLE
Sinon transformer doesn't seem to recognize sinon usages

### ISSUE THREAD

**Issue by josh-degraw** [skovhus/jest-codemods#325]
So I'm trying to migrate from mocha/chai/sinon, I have tried in the past but our usage of sinon had been a blocker, but I just saw that the Sinon transformer has been published!

However, when attempting to use it, it doesn't seem to do anything. I first tried just running the mocha/chai codemods first, but I saw the `Usage of package "sinon" might be incompatible with Jest; it's recommended the sinon transformer is run first` messages. So then I tried to run the `sinon` transformer first, but for every file it encounters it just says `no sinon for "file.js"`. Most (all?) of the files do `import sinon from 'sinon'`, and looking in the source I saw some `removeDefaultImport` function is used, so I thought maybe using a default import was blocking it, so I tried both using `import * as sinon from 'sinon'` and using named imports, and in both cases I still get the `no sinon for "file.js"` message.

Not sure if there's some other thing I'd need to do before it can work, but if so I'm having trouble identifying the issue. Any help would be much appreciated!

**Comment by josh-degraw** [comment]
Upon investigation, it seems like the problem is that the transformer assumes all `sinon` imports are being imported from `sinon-sandbox`. I'll submit a PR to address this.

**Comment by danbeam** [comment]
@skovhus @josh-degraw I think we can close this issue now (after https://github.com/skovhus/jest-codemods/pull/326)?
