### ISSUE TITLE
Mocha: before description removal

### ISSUE THREAD

**Issue by Vanuan** [skovhus/jest-codemods#34]
In mocha this is a valid before hook:

```
beforeEach('some initialization', () => {

});
```

In jasmine this fails with the error:

```
    TypeError: originalBodyFn.apply is not a function

      at Object.fn (node_modules/jest-jasmine2/build/jasmine-async.js:64:44)

```

I.e. transformer should remove descriptions from before/after hooks.

**Comment by skovhus** [comment]
Thanks for reporting this! Feel free to submit a pull request, maybe you want to give it a try? : )
