### ISSUE TITLE
convert jasmine clock methods to jest

### ISSUE THREAD

**Issue by lzhou0** [skovhus/jest-codemods#345]
Hi, I'm having trouble converting the following to jest. What is jest's equivalent for the clock() functions?

```
    jasmine.clock().uninstall();
    jasmine.clock().install();
    jasmine.clock().mockDate(mockTime);
```

Any support on this is greatly appreciated!

**Comment by jase88** [comment]
I think the equivalents would be
```typescript
jest.useRealTimers();
jest.useFakeTimers();
jest.setSystemTime(mockTime);
```

As far as I can see this should already be supported. Probably outdated issue?
