### ISSUE TITLE
Mocha migration does not rename files

### ISSUE THREAD

**Issue by pornel** [skovhus/jest-codemods#55]
I would expect migration to make files "seen" by jest. I have tests in `test/footest.js`, but AFAIK jest expects `test/foo.test.js`.

```sh
jest-codemods
```
> Processing 23 files...
> …
> All done.

```sh
jest
```
> No tests found

**Comment by skovhus** [comment]
Yes `jest-codemods` is more greedy and finds more files than `jest`... Renaming files seems a bit outside the scope of a codemod. 

@pornel But let me know if you want to give this a try.
