### ISSUE TITLE
Does not support Typescript `satisfies` keyword

### ISSUE THREAD

**Issue by danilofuchs** [skovhus/jest-codemods#553]
Transformation error (did not recognize object of type "TSSatisfiesExpression")
Error: did not recognize object of type "TSSatisfiesExpression"

**Comment by skovhus** [comment]
Thanks. Maybe upgrading jscodeshift would solve this. Contributions are more than welcome.

**Comment by skovhus** [comment]
Version 0.32.0 should work, can you test it out?
