### ISSUE TITLE
Codemod this keyword usage

### ISSUE THREAD

**Issue by skovhus** [skovhus/jest-codemods#57]
Newer versions of Jest doesn't support using `this` inside hooks (e.g. `beforeEach`). Instead variables defined outside the scope can achieve the same.

Although this project is mainly moving from other test runners and assertion libraries to Jest, we might be able to help people here...

Background https://github.com/facebook/jest/issues/3628#issuecomment-303339343

FYI @thymikee

**Comment by Brantron** [comment]
This would be such a big win!! I tried converting a large app to Jest and have ~180 of 1900 tests failing and ~80% stem from this issue.

**Comment by skovhus** [comment]
Let me know if you want to contribute. Or if you have some different examples of before and after fixing the issue. Would like to have some test cases to base the implementation on.

**Comment by AlanFoster** [comment]
Related PR: https://github.com/skovhus/jest-codemods/pull/61
