### ISSUE TITLE
Chai `.to.be.an('array')` conversion fails

### ISSUE THREAD

**Issue by IanVS** [skovhus/jest-codemods#59]
Chai's BDD style allows checking for an array with `expect(foo).to.be.an('array')`.  This is converted by jest-codemods into `expect (typeof foo).toBe('array')`.  However, the resulting spec will fail because `typeof` for an array is `"object"`.  

Perhaps a better transform would be:
```js
// input 
expect(foo).to.be.an('array');

// output
expect(Array.isArray(foo)).toBe(true);
```

**Comment by skovhus** [comment]
Thanks for reporting this! 

Do you want to help fixing it? : )

**Comment by IanVS** [comment]
It looks like it would just be adding another case to the switch [here](https://github.com/skovhus/jest-codemods/blob/master/src/transformers/chai-should.js#L109), right?  Looks simple enough, I should be able to knock out a PR in the next few days.

**Comment by skovhus** [comment]
Yeah, I guess the default case could handle this. : )

Let me know how it goes. 👍

**Comment by skovhus** [comment]
@IanVS I've released a fix for this as 0.10.2... Please let me know if it works for you. : ) 

Thanks

**Comment by IanVS** [comment]
Thanks!  Sorry I lost track of this.

**Comment by skovhus** [comment]
No worries. : )
