### ISSUE TITLE
jasmine Matchers with no direct equivalent are not transformed

### ISSUE THREAD

**Issue by jase88** [skovhus/jest-codemods#592]
I have noticed that some jasmine matchers that do not have a direct equivalent are not transformed.

For example:
-  `toBeTrue()` / `toBeFalse()`
- `toHaveBeenCalledOnceWith()`

https://jasmine.github.io/api/edge/matchers.html

there might be more, but these are just some I found.

In my view, there are two options for migration

a) Give the user the option of supplying the non-existent matchers via a dependency (such as [jest-extended](https://github.com/jest-community/jest-extended)) or supplying them themselves

b) Replace the matchers with more basic existing matchers, which may be more verbose

## Feature request
- It is possible to transform non-existent matchers. In my case these would be
  -  `expect(something).toBeTrue();` -> `expect(something).toBe(true);`
  -  `expect(something).toBeFalse();` -> `expect(something).toBe(false);`
  - `expect(method)toHaveBeenCalledOnceWith(something);` -> `expect(method).toHaveBeenCalledTimes(1); expect(method). toHaveBeenCalledWith(something);`
- this transformation happens either by default or can be activated by user input and/or CLI flag

**Comment by puglyfe** [comment]
i wrote a separate transform that covers all existing jasmine matchers. there are a few (e.g. `toHaveBeenCalledBefore`) that are really wonky to represent in jest, but i can share in a PR if it would be helpful.

**Comment by jase88** [comment]
Maybe it would be also good to document, which api parts are covered, partially covered, not implemented or are not covered because there is no real equivalent (with some further explanation). This could help developers that are migrating to guide to the manual parts. 

Of course also happy to see some PRs;)

**Comment by puglyfe** [comment]
here's what i came up with for jasmine matchers that don't exist in jest...

| Jasmine | Jest |
| - | - |
| `expect(foo).toBeTrue()` | `expect(foo).toBe(true)` |
`expect(foo).toBeFalse()` | `expect(foo).toBe(false)` |
`expect(mySpy).toHaveBeenCalledBefore(myOtherSpy)` | `expect(Math.min(...mySpy.mock.invocationOrder)).toBeLessThan(Math.min(...myOtherSpy.mock.invocationOrder))` |
`expect(foo).toBeNegativeInfinity()` | `expect(foo).toBe(-Infinity)` |
`expect(foo).toBePositiveInfinity()` | `expect(foo).toBe(Infinity)` |
`expect(mySpy).toHaveBeenCalledOnceWith('foo')` | `expect(mySpy.mock.calls).toEqual([['foo']])` |
`expect([1, 2]).toHaveSize(2)` | `expect([1, 2]).toHaveLength(2)` |
`expect(mySpyObj).toHaveSpyInteractions()` | `expect(Object.values(mySpyObj).some(spy => spy.mock?.calls?.length)).toBe(true)` |
`expect(() => someFunctionThatThrows()).toThrowMatching(thrown => thrown.message.includes('foo'))` | :x: |

`toHaveBeenCalledBefore` and `toHaveSpyInteractions` are both a bit strange, but the rest are pretty straightforward.

**Comment by jase88** [comment]
Okay I can also implement some if that helps. `toBeTrue()` / `toBeFalse()` should already exist
