### ISSUE TITLE
Release expect transformer and browser mode

### ISSUE THREAD

**Issue by skovhus** [skovhus/jest-codemods#62]
Jest is taking over https://www.npmjs.com/package/expect in an upcoming release. As part of this a codemod was developed (https://github.com/skovhus/jest-codemods/pull/39) and Jest browser support was added for `jest-matchers` (will be `expect@20+`) and other relevant packages (https://github.com/facebook/jest/issues/3360).

Background:
- https://github.com/skovhus/jest-codemods/pull/39
- https://github.com/facebook/jest/issues/1679

Before releasing this:
- [x] Jest release new `expect` package and document browser support
- [x] revert https://github.com/skovhus/jest-codemods/pull/39/commits/8b4bb3f932c56021f8705f60113263c66207efae

FYI @cpojer

**Comment by SimenB** [comment]
https://github.com/facebook/jest/pull/4345

**Comment by skovhus** [comment]
@SimenB thanks! We just need to coordinate this a bit with the Jest@21 release. Keep me in the loop.

**Comment by cpojer** [comment]
@skovhus please subscribe to https://github.com/facebook/jest/issues/4332 also
