### ISSUE TITLE
Mocha: do not convert `test` to `it`

### ISSUE THREAD

**Issue by avaly** [skovhus/jest-codemods#64]
Mocha transformer converts the `test` methods to `it`. However the latest Jest docs advertise the usage of `test` instead of `it`: http://facebook.github.io/jest/docs/en/api.html#testname-fn

**Comment by skovhus** [comment]
Yeah, makes sense to keep "test". 👍🏻

**Comment by skovhus** [comment]
Released as 0.11.2

Thanks for raising this @avaly
