### ISSUE TITLE
Unexpected conversion of .Ok to .toBeTruthy()

### ISSUE THREAD

**Issue by probablyup** [skovhus/jest-codemods#65]
This is a little weird, but in a repo I was converting there are some constants that are defined like:

```js
const MESSAGES = {
  Ok: 'x',
  Cancel: 'y',
};
```

And one of the codemods (I think the chai one) replaced `MESSAGES.Ok` with `MESSAGES.toBeTruthy()`.

**Comment by skovhus** [comment]
Thanks for reporting. Expecially the magic chai can be hard to avoid these kind of errors. Much easier with something like tape and Ava where we have a specific import/require we can look for. 

Did you run all transformers option in the CLI on the entire source code? Which test runner were your tests written in?

**Comment by probablyup** [comment]
It was Jest+Chai to just Jest. I believe I only ran the chai transformer
but might be misremembering.

**Comment by skovhus** [comment]
Released as 0.11.1, thanks for raising this @probablyup!
