### ISSUE TITLE
X to.be.within(A, B) converted to X =< A && X >= B

### ISSUE THREAD

**Issue by hermanbanken** [skovhus/jest-codemods#71]
https://github.com/skovhus/jest-codemods/blob/e3a3f6651eecd7fefc51714d7b4b639a2f14b3be/src/transformers/chai-should.test.js#L545-L558 is the wrong way around.

**Comment by skovhus** [comment]
Yeah that looks wrong. Thanks for reporting this! Would you like to submit a PR, then let me know. : )

**Comment by skovhus** [comment]
Fix will be out in the next version. Thanks for contributing @hermanbanken : )
