### ISSUE TITLE
ava: Support test.todo

### ISSUE THREAD

**Issue by SimenB** [skovhus/jest-codemods#79]
Just going from `test.todo('this should be a test some day')` to `test('this should be a test some day')` should be enough. As long as no implementation is provided, jest is happy

**Comment by skovhus** [comment]
Thanks 👍

**Comment by SimenB** [comment]
Awesome!

For reference: https://github.com/facebook/jest/pull/1775

**Comment by skovhus** [comment]
Thanks! Released as 0.13.4.

https://github.com/skovhus/jest-codemods/releases/tag/0.13.4
