### ISSUE TITLE
Issue with AVA codemod

### ISSUE THREAD

**Issue by xjamundx** [skovhus/jest-codemods#8]
Out of 21 tests I got this error 3 times:

```
peError: Cannot read property 'type' of undefined
    at getIdentifierFromExpression (/Users/jamuferguson/dev/paypal/p2pnodeweb/node_modules/jest-codemods/dist/utils/recast-helpers.js:17:13)
    at getIdentifierFromExpression (/Users/jamuferguson/dev/paypal/p2pnodeweb/node_modules/jest-codemods/dist/utils/recast-helpers.js:20:12)
    at getIdentifierFromExpression (/Users/jamuferguson/dev/paypal/p2pnodeweb/node_modules/jest-codemods/dist/utils/recast-helpers.js:20:12)
    at /Users/jamuferguson/dev/paypal/p2pnodeweb/node_modules/jest-codemods/dist/transformers/ava.js:163:79
    at Array.filter (native)
    at Collection.filter (/Users/jamuferguson/dev/paypal/p2pnodeweb/node_modules/jscodeshift/dist/Collection.js:60:46)
    at rewriteTestCallExpression (/Users/jamuferguson/dev/paypal/p2pnodeweb/node_modules/jest-codemods/dist/transformers/ava.js:162:12)
    at /Users/jamuferguson/dev/paypal/p2pnodeweb/node_modules/jest-codemods/dist/transformers/ava.js:173:29
    at Array.forEach (native)
    at avaToJest (/Users/jamuferguson/dev/paypal/p2pnodeweb/node_modules/jest-codemods/dist/transformers/ava.js:173:16)
```
It's confused by this fairly confusing code (simplified here of course):

```js
import test from 'ava'

test('should pass', t => {
	return shouldFail(t, 'hi')
})

function shouldFail(t, message) {
	return Promise.reject().catch(err => {
		t.same(err.message, message)
	})
}

```

**Comment by xjamundx** [comment]
No need to fix it for me or anything, but just a heads up.

**Comment by xjamundx** [comment]
It turns it fails even without the promise

```js
import test from 'ava'

test('should pass', t => {
	shouldFail(t, 'hi')
})

function shouldFail(t, message) {
	t.same('error', message)
}
```

**Comment by skovhus** [comment]
Thank you so much for sharing the code examples here. I'll look into a fix.

Did it work for you on the rest of the codebase?

**Comment by xjamundx** [comment]
There were some issues, so like the default paths don't work. The only seem to work when I type them from the command line. `jest-codemods public/js/**/__tests__/*.js` works by not running `jest-codesmods` without a path (even if I type the path during the command step), and I assume that's something to do with how you process paths vs. how the OS does it for you. Anyway, not a big deal.

Also had some issues installing globally, so i was just running it locally from `./node_modules/.bin/jest-codemods`

So far so good, not all the tests that transpiled are passing, but it's helping a lot

**Comment by skovhus** [comment]
Thank you for sharing. 

Based on your example I found some issues with how t properties were parsed. It should now be more stable now. And also handle AVA `t.same` and other deprecated AVA properties that I overlooked. fd5e

Can you give 0.2.4 a spin? 

As for the problem with global installment, which version did you try? Maybe you can try out 0.2.4 and see if you have the same problem.

Thanks!

**Comment by skovhus** [comment]
Version 0.2.5 should fix your issue with globs not working when not providing a path.

**Comment by xjamundx** [comment]
awesome! trying them now

**Comment by skovhus** [comment]
There is still some issues with not removing `t` for the case where you are passing it to a function.

Example:
```javascript
import test from 'ava'

test('should pass', t => {
    shouldFail(t, 'hi')
    return shouldFail2(t, 'hi')
})

function shouldFail(t, message) {
    t.same('error', message)
}

function shouldFail2(t, message) {
    return Promise.reject().catch(err => {
        t.same(err.message, message)
    })
}
```

Currently converts to
```javascript
it('should pass', () => {
    shouldFail(t, 'hi')
    return shouldFail2(t, 'hi')
})

function shouldFail(t, message) {
    expect('error').toEqual(message)
}

function shouldFail2(t, message) {
    return Promise.reject().catch(err => {
        expect(err.message).toEqual(message)
    })
}
```

Notice that `t` is undefined. It should either be removed or replaced with Jasmines `done` function.

**Comment by xjamundx** [comment]
cool, this is more than enough to get us started thanks!

**Comment by skovhus** [comment]
@xjamundx let me know if you find other bugs. : )
