### ISSUE TITLE
Upgrading from Expect 1.x without using Jest?

### ISSUE THREAD

**Issue by mjomble** [skovhus/jest-codemods#85]
I have a project with a custom test engine that has been using 1.x versions of mjackson's `expect` package for a while.
I would like to upgrade to the new version of the `expect` package, but keep my existing test engine instead of switching over to Jest.

Is this something that the "Expect@1.x (by mjackson)" codemod in this repo is meant to support or is it more for people who intend to switch over to Jest?

**Comment by skovhus** [comment]
The goal here is mostly to make the transition easier to Jest. 

But if you choose browser mode "Expect@1.x (by mjackson)" you get explicit import of the new version of expect (from Jest)... You should be able to get that to work with your existing test runner.

**Comment by mjomble** [comment]
Ah, I've been using `require('expect')` in tests that run on Node, so I picked the other option :)

Perhaps it could be better documented what the Node and browser options actually do? Or maybe even change the question so it's more clearly about explicit vs implicit requires?

**Comment by skovhus** [comment]
> Perhaps it could be better documented what the Node and browser options actually do? Or maybe even change the question so it's more clearly about explicit vs implicit requires?

I'm open for PRs if you want to help making this clearer. : )
