### ISSUE TITLE
chai.assert.approximately() arguments don't map to Jest's .toBeCloseTo()

### ISSUE THREAD

**Issue by mxmul** [skovhus/jest-codemods#93]
The chai-assert codemods will rewrite this:
```javascript
assert.approximately(x, 1, 0.1);
assert.closeTo(y, 25, 50);
```
as

```javascript
expect(x).toBeCloseTo(1, 0.1);
expect(y).toBeCloseTo(25, 50);
```

Which is almost always going to break tests, because the third argument in Chai's "[approximately](http://chaijs.com/api/assert/#method_approximately)" is a delta whereas the second argument to Jest's "[toBeCloseTo](https://facebook.github.io/jest/docs/en/expect.html#tobeclosetonumber-numdigits)" is number of matching digits.

A more correct codemod output would probably be something like:
```javascript
expect(Math.abs(x - 1)).toBeLessThan(0.1);
expect(Math.abs(y - 25)).toBeLessThan(50);
```

**Comment by skovhus** [comment]
Hi @mxmul!

Thanks for reporting this. Let me know if you want to give it a stab.

**Comment by mxmul** [comment]
sure, I'll take a stab at it
