### ISSUE TITLE
chai-assert conversions fail when using chai default export

### ISSUE THREAD

**Issue by mxmul** [skovhus/jest-codemods#94]
The codemod is not able to transform calls like "chai.assert.equal(...)" to Jest assertions. I would expect that either this:
```javascript
import { assert } from 'chai';

assert.equal(1, 1);
```

or this:
```javascript
import chai from 'chai';

chai.assert.equal(1, 1);
```

to be transformed to this:
```
expect(1).toEqual(1);
```

but only the first is actually fixed.

**Comment by skovhus** [comment]
Thanks for reporting this @mxmul 

Yeah, I haven't seen people using assert like that... But that is clearly a bug that we should fix. : )

Let me know if you want to try to fix it.

**Comment by mxmul** [comment]
sure, I can take a stab at it :)

**Comment by VinSpee** [comment]
hi! This is still not transforming for me:

```diff
     // Host tests
-    context('Host testing', () => {
+    describe('Host testing', () => {
       imageHosts.forEach((imageHost) => {
-        it(`should provide secure Crushinator URLs for images hosted on ${imageHost}`, () => {
-          const url = `//${imageHost}/image.jpg`;
-
-          assert.equal(
-            crushinator.crush(`http:${url}`, { width: 200 }),
-            `https://pi.cdn.com/r/${imageHost}/image.jpg?w=200`,
-          );
-
-          assert.equal(
-            crushinator.crush(`https:${url}`, { width: 200 }),
-            `https://pi.cdn.com/r/${imageHost}/image.jpg?w=200`,
-          );
-        });
+        test(
+          `should provide secure Crushinator URLs for images hosted on ${imageHost}`,
+          () => {
+            const url = `//${imageHost}/image.jpg`;
+
+            assert.equal(
+              crushinator.crush(`http:${url}`, { width: 200 }),
+              `https://pi.cdn.com/r/${imageHost}/image.jpg?w=200`,
+            );
+
+            assert.equal(
+              crushinator.crush(`https:${url}`, { width: 200 }),
+              `https://pi.cdn.com/r/${imageHost}/image.jpg?w=200`,
+            );
+          }
+        );
       });
     });
```

am I doing something wrong?

**Comment by skovhus** [comment]
@mxmul any idea what is the issue here? : )

**Comment by VinSpee** [comment]
i played around with my imports a bit and got it to work correctly, I was doing an

```js
import expect from 'expect';
```

changing it to
```js
import { expect } from 'chai';
```

and specifying the chai transform w/ expect worked.

Thoughts on why this might be?

**Comment by skovhus** [comment]
@VinSpee ... So are you using `expect` and `chai`? Or only one of them?

**Comment by VinSpee** [comment]
my bad. everywhere I wrote `expect`, i meant `assert`.

**Comment by skovhus** [comment]
Ahh ok.

If you have time, it would be super useful if you could create a new issue with a description of the specific issue you had and how you went around it. : )

Would like to close this one.
