### ISSUE TITLE
Check if git directory is clean upfront.

### ISSUE THREAD

**Issue by frontalicious-martijn** [skovhus/jest-codemods#99]
Love your tool! To make it even more friendly; Can you please change the message: "ERROR: Git directory is not clean. Refusing to continue." ?

* Please show this message _before_ asking what to migrate. Saves time and frustration.
* Because you ask it upfront, it does not have to be this aggressive error but it could be something like: "Thank you for using jest-codemods! But before we continue, please stash your git changes."

**Comment by skovhus** [comment]
Love the idea! Do you want to do a PR for this? : )

**Comment by frontalicious-martijn** [comment]
I could try :-)

**Comment by guyellis** [comment]
I was just looking at doing a PR for this but master is not installing "clean" - this is what I get using Node 9.5 and npm 5.6.0 and if I do `npm i`

```
> jest-codemods@0.13.9 prepare /home/guy/source/jest-codemods
> npm run clean && npm run check:bail && npm run build


> jest-codemods@0.13.9 clean /home/guy/source/jest-codemods
> rm -rf lib coverage npm-debug.log dist


> jest-codemods@0.13.9 check:bail /home/guy/source/jest-codemods
> eslint src && npm run test:cov


/home/guy/source/jest-codemods/src/transformers/expect.js
  138:101  error  Delete `matcherNode`                                                                        prettier/prettier
  139:17   error  Replace `.arguments.length` with `matcherNode.arguments.length⏎············`                prettier/prettier
  272:29   error  Replace `path.value.property` with `⏎····························path.value.property.name`  prettier/prettier
  273:25   error  Delete `····.name`                                                                          prettier/prettier

✖ 4 problems (4 errors, 0 warnings)
  4 errors, 0 warnings potentially fixable with the `--fix` option.
```

**Comment by skovhus** [comment]
@guyellis please see https://github.com/skovhus/jest-codemods#contributing

We use `yarn` here. If you use `npm` then you would not get the correct version as we don't store the transient dependencies for `npm`.

Thanks

**Comment by skovhus** [comment]
I implemented and released this April, but forgot to close this issue. :)

Thanks @guyellis @frontalicious-martijn

**Comment by mikelhamer** [comment]
I'm getting this message even though I have no uncommited changes. Any ideas?
